### PR TITLE
Fix static tests

### PR DESCRIPTION
**Pull request by skovalenk**
### Related Pull Requests
https://github.com/magento/catalog-storefront/pull/452

### Fixed Issues (if relevant)

1. Fixes magento/storefront-message-broker#<issue_number>

### Code Review Checklist (*)

See detailed [checklist](https://github.com/magento/storefront-message-broker/blob/develop/dev/docs/projectAgreements/Code-Review-checklist.md)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
  - expected results in test verified with data from fixture
- [ ] no backward incompatible changes
- [ ] Class usage: magento/storefront-message-broker repo don't use directly classes from magento/saas-export repo and vise-verse
  - Check composer.json dependencies
- [ ] Legacy code is deleted

### CODE REVIEW

**Comment by le0n4ik** [comment]
@magento run all tests

**Comment by le0n4ik** [comment]
@magento run Functional Tests CE

**Comment by le0n4ik** [comment]
@magento run Functional Tests EE

**Comment by le0n4ik** [comment]
Made changes wouldn't affect functional tests. So can assume that builds are green

**Comment by le0n4ik** [comment]
@magento import pr to magento-commerce/storefront-message-broker

**Comment by magento-engcom-team** [comment]
@le0n4ik the pull request successfully imported.

**Comment by le0n4ik** [comment]
@skovalenk please squash your commits with more descriptive comment (not "Some commit")

**Pull request closed without merging**
